apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    type: front-end
  name: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
      type: front-end
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        type: front-end
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        ports:
        - containerPort: 80
status: {}
