apiVersion: v1
kind: Service
metadata:
  name: nginx-cip
  labels:
    name: nginx
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx
    type: front-end
