apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
    type: front-end
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    targetPort: 80
  selector:
    app: nginx
    type: front-end


