apiVersion: v1
kind: Service
metadata:
  name: dash-lb
  labels:
    name: dash
    type: front-end
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 30082
    targetPort: 80
  selector:
    app: dash
    type: front-end
