apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  labels:
    name: nginx
    type: front-end
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30081
    targetPort: 80
  selector:
    app: nginx
    type: front-end


